{{- include "linkd.validate" . -}}
{{- $workloads := (include "linkd.workloads" . | fromYaml).items -}}
{{- $secrets := dict -}}
{{- range $w := $workloads -}}
{{- if not $w.external -}}
{{- $data := get $secrets $w.secret | default dict -}}
{{- if hasKey $data $w.key }}{{ fail (printf "%s 中配置 key 重复: %s" $w.secret $w.key) }}{{ end -}}
{{- $_ := set $data $w.key (include "linkd.configuration" (dict "root" $ "workload" $w) | b64enc) -}}
{{- $_ := set $secrets $w.secret $data -}}
{{- end -}}
{{- end -}}
{{- range $name, $data := $secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
type: Opaque
data:
  {{- toYaml $data | nindent 2 }}
{{- end }}
