{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "linkd.fullname" .) }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
automountServiceAccountToken: false
{{- end }}
