{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "linkd.fullname" . }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- $labels := mergeOverwrite (deepCopy .Values.commonLabels) (dict "app.kubernetes.io/name" (.Values.nameOverride | default .Chart.Name) "app.kubernetes.io/instance" .Release.Name "app.kubernetes.io/managed-by" .Release.Service) .Values.metrics.serviceMonitor.labels }}
    {{- toYaml $labels | nindent 4 }}
  {{- with mergeOverwrite (deepCopy .Values.commonAnnotations) .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames: [{{ .Release.Namespace | quote }}]
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      linkd/metrics: "true"
  {{- with .Values.metrics.serviceMonitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  sampleLimit: {{ .Values.metrics.serviceMonitor.sampleLimit }}
  targetLimit: {{ .Values.metrics.serviceMonitor.targetLimit }}
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
