FROM centos:7
RUN mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup && cd /etc/yum.repos.d/ && curl -L http://mirrors.163.com/.help/CentOS7-Base-163.repo > CentOS7-Base-163.repo && yum makecache && yum -y update && \
yum -y install wget && \
yum -y install gcc && \
yum -y install git  && \
mkdir /goroot && cd /goroot && wget --no-check-certificate https://studygolang.com/dl/golang/go1.15.11.linux-amd64.tar.gz && mv go1.15.11.linux-amd64.tar.gz go.tar.gz && tar -xvf go.tar.gz
RUN cd /tmp && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.sh && chmod +x /tmp/rustup.sh && ./rustup.sh -y && source $HOME/.cargo/env && \
echo "/bin/bash\n go get github.com/influxdata/pkg-config" >> /root/build.sh && chmod +x /root/build.sh

ENV GOROOT=/goroot/go 
ENV GOPATH=/gowork 
ENV PATH=${GOROOT}/bin:${PATH}
ENV PATH=${GOPATH}/bin:${PATH}
ENV PATH=/goroot:${PATH}

RUN go get github.com/influxdata/pkg-config && \
mkdir /goroot/temp &&\
cp $GOPATH/bin/pkg-config /goroot/temp/pkg-config && chmod +x /goroot/temp/pkg-config
