// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/query/ts": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "query monitor by ts",
                "operationId": "ts-query-request",
                "parameters": [
                    {
                        "type": "string",
                        "default": "00-3967ac0f1648bf0216b27631730d7eb9-8e3c31d5109e78dd-01",
                        "description": "TraceID",
                        "name": "traceparent",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "username:goodman",
                        "description": "来源",
                        "name": "Bk-Query-Source",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "bkcc__2",
                        "description": "空间UID",
                        "name": "X-Bk-Scope-Space-Uid",
                        "in": "header"
                    },
                    {
                        "description": "json data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structured.QueryTs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PromData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrResponse"
                        }
                    }
                }
            }
        },
        "/query/ts/exemplar": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "query monitor by ts exemplar",
                "operationId": "ts-query-exemplar-request",
                "parameters": [
                    {
                        "type": "string",
                        "default": "00-3967ac0f1648bf0216b27631730d7eb9-8e3c31d5109e78dd-01",
                        "description": "TraceID",
                        "name": "traceparent",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "username:goodman",
                        "description": "来源",
                        "name": "Bk-Query-Source",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "bkcc__2",
                        "description": "空间UID",
                        "name": "X-Bk-Scope-Space-Uid",
                        "in": "header"
                    },
                    {
                        "description": "json data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structured.QueryTs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PromData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrResponse"
                        }
                    }
                }
            }
        },
        "/query/ts/promql": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "query monitor by promql",
                "operationId": "ts-query-request-promql",
                "parameters": [
                    {
                        "type": "string",
                        "default": "00-3967ac0f1648bf0216b27631730d7eb9-8e3c31d5109e78dd-01",
                        "description": "TraceID",
                        "name": "traceparent",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "username:goodman",
                        "description": "来源",
                        "name": "Bk-Query-Source",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "bkcc__2",
                        "description": "空间UID",
                        "name": "X-Bk-Scope-Space-Uid",
                        "in": "header"
                    },
                    {
                        "description": "json data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structured.QueryPromQL"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PromData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ErrResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "http.PromData": {
            "type": "object",
            "properties": {
                "series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.TablesItem"
                    }
                },
                "status": {
                    "$ref": "#/definitions/metadata.Status"
                }
            }
        },
        "http.TablesItem": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "group_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "group_values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "metric_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {}
                    }
                }
            }
        },
        "metadata.Status": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "structured.AggregateMethod": {
            "type": "object",
            "properties": {
                "dimensions": {
                    "description": "Dimensions 聚合维度",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "bk_target_ip",
                        "bk_target_cloud_id"
                    ]
                },
                "method": {
                    "description": "Method 聚合方法",
                    "type": "string",
                    "example": "mean"
                },
                "without": {
                    "description": "Without",
                    "type": "boolean"
                }
            }
        },
        "structured.ConditionField": {
            "type": "object",
            "properties": {
                "field_name": {
                    "description": "DimensionName 过滤字段",
                    "type": "string",
                    "example": "bk_biz_id"
                },
                "op": {
                    "description": "Operator 操作符，包含：eq,ne,erq,nreq,contains,ncontains",
                    "type": "string",
                    "example": "contains"
                },
                "value": {
                    "description": "Value 查询值",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2"
                    ]
                }
            }
        },
        "structured.Conditions": {
            "type": "object",
            "properties": {
                "condition_list": {
                    "description": "ConditionList 组合条件，长度 = len(FieldList) - 1的数组，支持 and,or",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "and"
                    ]
                },
                "field_list": {
                    "description": "FieldList 查询条件",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structured.ConditionField"
                    }
                }
            }
        },
        "structured.Query": {
            "type": "object",
            "properties": {
                "conditions": {
                    "description": "Conditions 过滤条件",
                    "allOf": [
                        {
                            "$ref": "#/definitions/structured.Conditions"
                        }
                    ]
                },
                "dimensions": {
                    "description": "Dimensions promQL 使用维度",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "bk_target_ip",
                        "bk_target_cloud_id"
                    ]
                },
                "field_name": {
                    "description": "FieldName 查询指标",
                    "type": "string",
                    "example": "usage"
                },
                "function": {
                    "description": "AggregateMethodList 维度聚合函数",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structured.AggregateMethod"
                    }
                },
                "limit": {
                    "description": "Limit 点数限制数量",
                    "type": "integer",
                    "example": 0
                },
                "offset": {
                    "description": "Offset 偏移量",
                    "type": "string",
                    "example": ""
                },
                "offset_forward": {
                    "description": "OffsetForward 偏移方向，默认 false 为向前偏移",
                    "type": "boolean",
                    "example": false
                },
                "reference_name": {
                    "description": "ReferenceName 别名，用于表达式计算",
                    "type": "string",
                    "example": "a"
                },
                "slimit": {
                    "description": "Slimit 维度限制数量",
                    "type": "integer",
                    "example": 0
                },
                "start_or_end": {
                    "description": "StartOrEnd @-modifier 标记，start or end",
                    "type": "integer"
                },
                "table_id": {
                    "description": "TableID 数据实体ID，容器指标可以为空",
                    "type": "string",
                    "example": "system.cpu_summary"
                },
                "time_aggregation": {
                    "description": "TimeAggregation 时间聚合方法",
                    "allOf": [
                        {
                            "$ref": "#/definitions/structured.TimeAggregation"
                        }
                    ]
                },
                "timestamp": {
                    "description": "Timestamp @-modifier 标记",
                    "type": "integer"
                },
                "vector_offset": {
                    "description": "VectorOffset",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                }
            }
        },
        "structured.QueryPromQL": {
            "type": "object",
            "properties": {
                "bk_biz_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "max_source_resolution": {
                    "type": "string"
                },
                "not_align_influxdb": {
                    "description": "不与influxdb对齐",
                    "type": "boolean"
                },
                "promql": {
                    "type": "string"
                },
                "slimit": {
                    "type": "integer"
                },
                "start": {
                    "type": "string"
                },
                "step": {
                    "type": "string"
                }
            }
        },
        "structured.QueryTs": {
            "type": "object",
            "properties": {
                "down_sample_range": {
                    "description": "DownSampleRange 降采样：大于Step才能生效，可以为空",
                    "type": "string",
                    "example": "5m"
                },
                "end_time": {
                    "description": "End 结束时间：单位为毫秒的时间戳",
                    "type": "string",
                    "example": "1657851600"
                },
                "metric_merge": {
                    "description": "MetricMerge 表达式：支持所有PromQL语法",
                    "type": "string",
                    "example": "a"
                },
                "query_list": {
                    "description": "QueryList 查询实例",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structured.Query"
                    }
                },
                "space_uid": {
                    "description": "SpaceUid 空间ID",
                    "type": "string"
                },
                "start_time": {
                    "description": "Start 开始时间：单位为毫秒的时间戳",
                    "type": "string",
                    "example": "1657848000"
                },
                "step": {
                    "description": "Step 步长：最终返回的点数的时间间隔",
                    "type": "string",
                    "example": "1m"
                }
            }
        },
        "structured.TimeAggregation": {
            "type": "object",
            "properties": {
                "function": {
                    "description": "Function 时间聚合方法",
                    "type": "string",
                    "example": "avg_over_time"
                },
                "window": {
                    "description": "Window 聚合周期",
                    "type": "string",
                    "example": "60s"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
