// Tencent is pleased to support the open source community by making
// 蓝鲸智云 - 监控平台 (BlueKing Monitor) available.
// Copyright (C) 2017-2025 Tencent. All rights reserved.
// Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.

package contract

import (
	"encoding/hex"
	"testing"
)

// canonicalBranchExpectation pins what one branch does today. Accepted output
// is stored as hex rather than as the bytes themselves: two earlier revisions
// of these tests wrote escape sequences literally and a tool folded them into
// the characters they denote, once splitting a string literal across lines and
// once putting a raw NUL in the source. Neither failed loudly. Hex cannot be
// folded into anything.
// The rejection text is hex for the same reason, and the reason is not
// hypothetical: the duplicate-field message echoes the offending key verbatim,
// so a rejection string can carry any bytes the input carried. Generating one
// of those as a JSON string literal emitted the astral character as a
// surrogate pair - correct JSON, and not compilable Go, which wants a single
// eight-digit escape and rejects lone surrogate halves. The build caught that
// one. Hex has one meaning in every language that reads this file, so nothing
// downstream has to agree about escapes.
type canonicalBranchExpectation struct {
	accept       bool
	wantHex      string
	wantErrorHex string
}

// canonicalBranchExpectations was generated by running the branch probes
// against the implementation being replaced, not written by hand. Transcribing
// eighty byte strings is where a wrong expectation would enter, and a wrong
// expectation in the denominator is worse than a missing one: it looks like
// coverage.
//
// Regenerate with:
//
//	CANONICAL_BRANCH_DISCOVERY=1 go test ./contract/ -run TestCanonicalBranchDiscovery -v
//
// Regenerating is only correct while CanonicalJSONV2 is still the old
// implementation. Once it is replaced, this table is the thing the replacement
// is checked against, and regenerating it from the replacement would erase the
// check.
var canonicalBranchExpectations = map[string]canonicalBranchExpectation{
	"null":                            {accept: true, wantHex: "6e756c6c"},
	"true":                            {accept: true, wantHex: "74727565"},
	"false":                           {accept: true, wantHex: "66616c7365"},
	"int":                             {accept: true, wantHex: "31"},
	"negative":                        {accept: true, wantHex: "2d3432"},
	"minus zero":                      {accept: true, wantHex: "2d30"},
	"trailing zeros":                  {accept: true, wantHex: "312e3030"},
	"exponent lower":                  {accept: true, wantHex: "316533"},
	"exponent upper signed":           {accept: true, wantHex: "31452b33"},
	"big int beyond float64":          {accept: true, wantHex: "39303037313939323534373430393933"},
	"very long number":                {accept: true, wantHex: "31323334353637383930313233343536373839303132333435363738393031323334353637383930"},
	"empty string":                    {accept: true, wantHex: "2222"},
	"empty array":                     {accept: true, wantHex: "5b5d"},
	"empty object":                    {accept: true, wantHex: "7b7d"},
	"object keys already sorted":      {accept: true, wantHex: "7b2261223a312c2262223a327d"},
	"object keys reversed":            {accept: true, wantHex: "7b2261223a312c2262223a327d"},
	"object keys numeric-ish":         {accept: true, wantHex: "7b223130223a312c2239223a327d"},
	"object keys unicode":             {accept: true, wantHex: "7b2261223a322c22c3a9223a317d"},
	"nested object keys reversed":     {accept: true, wantHex: "7b227a223a7b2261223a322c2262223a317d7d"},
	"array order preserved":           {accept: true, wantHex: "5b332c312c325d"},
	"quote":                           {accept: true, wantHex: "22615c226222"},
	"backslash":                       {accept: true, wantHex: "22615c5c6222"},
	"solidus escaped in input":        {accept: true, wantHex: "22612f6222"},
	"newline escape":                  {accept: true, wantHex: "22615c6e6222"},
	"tab escape":                      {accept: true, wantHex: "22615c746222"},
	"carriage return escape":          {accept: true, wantHex: "22615c726222"},
	"backspace escape":                {accept: true, wantHex: "22615c626222"},
	"formfeed escape":                 {accept: true, wantHex: "22615c666222"},
	"nul escape":                      {accept: true, wantHex: "22615c75303030306222"},
	"unit separator escape":           {accept: true, wantHex: "22615c75303031666222"},
	"del literal":                     {accept: true, wantHex: "22617f6222"},
	"html chars literal":              {accept: true, wantHex: "22613c623e63266422"},
	"html chars escaped in input":     {accept: true, wantHex: "22613c6222"},
	"non ascii literal":               {accept: true, wantHex: "22c3a922"},
	"non ascii escaped in input":      {accept: true, wantHex: "22c3a922"},
	"cjk literal":                     {accept: true, wantHex: "22e7bbb4e5baa622"},
	"line separator literal":          {accept: true, wantHex: "2261e280a86222"},
	"line separator escaped in input": {accept: true, wantHex: "2261e280a86222"},
	"paragraph separator literal":     {accept: true, wantHex: "2261e280a96222"},
	"astral literal":                  {accept: true, wantHex: "22f09f988022"},
	"astral escaped in input":         {accept: true, wantHex: "22f09f988022"},
	"closed string type":              {accept: true, wantHex: "22706c61696e22"},
	"closed string with quote":        {accept: true, wantHex: "22615c226222"},
	"closed string non ascii":         {accept: true, wantHex: "22c3a922"},
	"closed string line separator":    {accept: true, wantHex: "2261e280a86222"},
	"closed string astral":            {accept: true, wantHex: "22f09f988022"},
	"closed struct":                   {accept: true, wantHex: "7b226e616d65223a226e222c2276616c7565223a317d"},
	"closed int":                      {accept: true, wantHex: "3432"},
	"closed float":                    {accept: true, wantHex: "312e35"},
	"closed bool":                     {accept: true, wantHex: "74727565"},
	"closed slice of string":          {accept: true, wantHex: "5b2262222c2261225d"},
	"map string any":                  {accept: true, wantHex: "7b2261223a312c2262223a327d"},
	"closed struct declaration order not alphabetical": {accept: true, wantHex: "7b226170706c65223a322c227a65627261223a317d"},
	"pointer to closed struct":                         {accept: true, wantHex: "7b226170706c65223a322c227a65627261223a317d"},
	"byte slice input":                                 {accept: true, wantHex: "7b2261223a322c2262223a317d"},
	"json marshaler type":                              {accept: true, wantHex: "7b2261223a322c2262223a317d"},
	"text marshaler type":                              {accept: true, wantHex: "22746578742d76616c756522"},
	"key needing escape":                               {accept: true, wantHex: "7b22615c2262223a317d"},
	"key with control char escape":                     {accept: true, wantHex: "7b22615c753030303162223a317d"},
	"duplicate keys differing by escape form":          {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a206475706c6963617465206669656c642061"},
	"keys differing only by escape form sorted":        {accept: true, wantHex: "7b2261223a322c2262223a317d"},
	"nested empty containers":                          {accept: true, wantHex: "7b2261223a7b7d2c2262223a5b5d7d"},
	"deep nesting":                                     {accept: true, wantHex: "7b2261223a7b2262223a7b2263223a7b2264223a5b312c7b2265223a327d5d7d7d7d7d"},
	"array of objects keys reversed":                   {accept: true, wantHex: "5b7b2261223a322c2262223a317d2c7b2263223a342c2264223a337d5d"},
	"object value is string with escapes":              {accept: true, wantHex: "7b226b223a22765c6e77227d"},
	"empty key":                                        {accept: true, wantHex: "7b22223a312c2261223a327d"},
	"key that is a prefix of another":                  {accept: true, wantHex: "7b2261223a322c226162223a317d"},
	"duplicate keys surrogate pair versus literal":     {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a206475706c6963617465206669656c6420f09f9880"},
	"keys sorted across literal astral and ascii":      {accept: true, wantHex: "7b2261223a322c22f09f9880223a317d"},
	"exponent overflowing float64":                     {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e73206e6f6e2d66696e69746520666c6f6174696e672d706f696e74206e756d626572"},
	"negative exponent overflowing float64":            {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e73206e6f6e2d66696e69746520666c6f6174696e672d706f696e74206e756d626572"},
	"decimal exponent overflowing float64":             {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e73206e6f6e2d66696e69746520666c6f6174696e672d706f696e74206e756d626572"},
	"exponent underflowing to zero":                    {accept: true, wantHex: "31652d393939"},
	"exponent overflow inside object":                  {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e73206e6f6e2d66696e69746520666c6f6174696e672d706f696e74206e756d626572"},
	"exponent overflow inside array":                   {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e73206e6f6e2d66696e69746520666c6f6174696e672d706f696e74206e756d626572"},
	"exponent at the float64 boundary":                 {accept: true, wantHex: "312e3739373639333133343836323331353765333038"},
	"exponent just past the float64 boundary":          {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e73206e6f6e2d66696e69746520666c6f6174696e672d706f696e74206e756d626572"},
	"empty payload":                                    {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a2063616e6f6e6963616c5f6a736f6e3a206d75737420636f6e7461696e206e6f6e2d656d707479205554462d38204a534f4e20776974686f757420424f4d"},
	"whitespace only":                                  {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20454f46"},
	"bom prefixed":                                     {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a2063616e6f6e6963616c5f6a736f6e3a206d75737420636f6e7461696e206e6f6e2d656d707479205554462d38204a534f4e20776974686f757420424f4d"},
	"invalid utf8":                                     {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a2063616e6f6e6963616c5f6a736f6e3a206d75737420636f6e7461696e206e6f6e2d656d707479205554462d38204a534f4e20776974686f757420424f4d"},
	"lone high surrogate":                              {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e7320756e706169726564206869676820737572726f6761746520657363617065"},
	"lone low surrogate":                               {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e7320756e706169726564206c6f7720737572726f6761746520657363617065"},
	"duplicate keys":                                   {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a206475706c6963617465206669656c642061"},
	"duplicate keys nested":                            {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a206475706c6963617465206669656c642061"},
	"trailing value":                                   {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e7320747261696c696e672076616c7565"},
	"malformed":                                        {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20756e7465726d696e61746564206f626a656374"},
	"leading zero number":                              {wantErrorHex: "636f6e74726163742076616c69646174696f6e3a206a736f6e3a20636f6e7461696e7320747261696c696e672076616c7565"},
	"leading whitespace":                               {accept: true, wantHex: "31"},
	"trailing whitespace":                              {accept: true, wantHex: "31"},
}

// TestCanonicalBranchTableIsReachableAndPinned does two jobs at once.
//
// Reachability: every branch in the denominator has an input that reaches it,
// and running that input produces the stated result. A branch that cannot be
// reached is removed rather than left to make coverage permanently short.
//
// Pinning: the stated result is the behaviour a replacement has to reproduce
// byte for byte. This test is what turns the table from a list of intentions
// into a check.
func TestCanonicalBranchTableIsReachableAndPinned(t *testing.T) {
	probes := canonicalBranchProbes()
	if len(probes) != len(canonicalBranchExpectations) {
		t.Fatalf("%d probes against %d expectations; the denominator and the table have drifted apart",
			len(probes), len(canonicalBranchExpectations))
	}
	seen := make(map[string]bool, len(probes))
	for _, probe := range probes {
		if seen[probe.name] {
			t.Fatalf("branch %q appears twice; two branches sharing a name cannot both be counted as covered", probe.name)
		}
		seen[probe.name] = true
		want, ok := canonicalBranchExpectations[probe.name]
		if !ok {
			t.Fatalf("branch %q has no expectation; an unpinned branch is not part of the denominator", probe.name)
		}
		t.Run(probe.name, func(t *testing.T) {
			out, err := CanonicalJSONV2(probe.value)
			if want.accept {
				if err != nil {
					t.Fatalf("want accept, got error %v", err)
				}
				if got := hex.EncodeToString(out); got != want.wantHex {
					t.Fatalf("canonical bytes moved:\n want %s\n got  %s", want.wantHex, got)
				}
				return
			}
			wantError, decodeErr := hex.DecodeString(want.wantErrorHex)
			if decodeErr != nil {
				t.Fatalf("expectation is not hex: %v", decodeErr)
			}
			if err == nil {
				t.Fatalf("want rejection %q, got accept %s", wantError, hex.EncodeToString(out))
			}
			if err.Error() != string(wantError) {
				t.Fatalf("rejection text moved:\n want %q\n got  %q", wantError, err.Error())
			}
		})
	}
}
