// Tencent is pleased to support the open source community by making
// 蓝鲸智云 - 监控平台 (BlueKing - Monitor) available.
// Copyright (C) 2022 THL A29 Limited, a Tencent company. All rights reserved.
// Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
// You may obtain a copy of the License at http://opensource.org/licenses/MIT
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

package procport_test

import (
	"context"
	_ "embed"
	"fmt"
	"testing"

	"github.com/stretchr/testify/suite"

	"github.com/TencentBlueKing/bkmonitor-datalink/pkg/transfer/define"
	"github.com/TencentBlueKing/bkmonitor-datalink/pkg/transfer/template/etl/procport"
	"github.com/TencentBlueKing/bkmonitor-datalink/pkg/transfer/testsuite"
)

// ProcPortTest
type ProcPortTest struct {
	testsuite.ETLSuite
}

//go:embed fixture/proc_port_test_data.json
var procPortData string

// TestUsage :
func (s *ProcPortTest) TestUsage() {
	s.RunN(19,
		procPortData,
		procport.NewPerformanceProcPortProcessor(s.CTX, "test"),
		func(result map[string]interface{}) {
			var deviceName string
			if deviceValue, ok := result["dimensions"].(map[string]interface{})["listen"].(string); ok {
				deviceName = deviceValue
			} else {
				panic(fmt.Errorf("convert fail no listen found in %v", result))
			}
			s.EqualRecord(result, map[string]interface{}{
				"[]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "127.0.0.1",
						"bk_supplier_id":      "0",
						"display_name":        "mytest1_exporter",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[]",
						"nonlisten":           "[9601,9602,9726]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "mytest1_exporter",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 0.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[3888,2181]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "zk-java",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[3888,2181]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "org.apache.zookeeper.server.quorum.QuorumPeerMain",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "java",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[6379]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "redis-server",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[6379]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         ":6379",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "redis-server",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[16379]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "redis-sentinel",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[16379]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "sentinel",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "redis-server",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[27017]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "mongod",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[27017]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "mongod",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[8444,8008]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "job-java",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[8444,8008]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "job.conf",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "java",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[8301,8500,53]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "consul-agent",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[8301,8500,53]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "consul",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[33083]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_webserver",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[33083]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_webserver",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[32002]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_toposerver",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[32002]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_toposerver",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[32003]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_procserver",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[32003]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_procserver",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[31003]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_proccontroller",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[31003]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_proccontroller",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[31001]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_objectcontroller",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[31001]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_objectcontroller",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[32001]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_hostserver",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[32001]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_hostserver",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[31002]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_hostcontroller",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[31002]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_hostcontroller",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[32005]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_eventserver",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[32005]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_eventserver",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[33084]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_datacollection",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[33084]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_datacollection",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[31004]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_auditcontroller",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[31004]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_auditcontroller",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[33031]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_apiserver",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[33031]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_apiserver",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
				"[32004]": map[string]interface{}{
					"dimensions": map[string]interface{}{
						"bind_ip":             "",
						"bk_supplier_id":      "0",
						"display_name":        "cmdb_adminserver",
						"hostname":            "VM_1_10_centos",
						"ip":                  "127.0.0.1",
						"bk_target_ip":        "127.0.0.1",
						"listen":              "[32004]",
						"nonlisten":           "[]",
						"not_accurate_listen": "[]",
						"param_regex":         "",
						"bk_cloud_id":         "0",
						"bk_target_cloud_id":  "0",
						"bk_agent_id":         "010000525400c48bdc1670385834306k",
						"bk_biz_id":           "2",
						"bk_host_id":          "30145",
						"bk_target_host_id":   "30145",
						"proc_name":           "cmdb_adminserver",
						"protocol":            "tcp",
					},
					"metrics": map[string]interface{}{"port_health": 1.0, "proc_exists": 1.0},
					"time":    1554094238,
				},
			}[deviceName].(map[string]interface{}))
		},
	)
}

func (s *ProcPortTest) TestDisabledBizIDs() {
	processor := procport.NewPerformanceProcPortProcessor(s.CTX, "test")
	processor.DisabledBizIDs = map[string]struct{}{"0": {}}
	s.RunN(0,
		procPortData,
		processor,
		func(result map[string]interface{}) {},
	)
}

// TestProcPortTest :
func TestProcPortTest(t *testing.T) {
	suite.Run(t, new(ProcPortTest))
}

// BenchmarkPerformanceProcPortProcessor_Process :
func BenchmarkPerformanceProcPortProcessor_Process(b *testing.B) {
	testsuite.ETLBenchmarkTest(b, func(ctx context.Context, name string) define.DataProcessor {
		return procport.NewPerformanceProcPortProcessor(ctx, name)
	}, []byte(procPortData))
}
