// Code generated by go-queryset. DO NOT EDIT.
package bcs

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jinzhu/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set BCSPodQuerySet

// BCSPodQuerySet is an queryset type for BCSPod
type BCSPodQuerySet struct {
	db *gorm.DB
}

// NewBCSPodQuerySet constructs new BCSPodQuerySet
func NewBCSPodQuerySet(db *gorm.DB) BCSPodQuerySet {
	return BCSPodQuerySet{
		db: db.Model(&BCSPod{}),
	}
}

func (qs BCSPodQuerySet) w(db *gorm.DB) BCSPodQuerySet {
	return NewBCSPodQuerySet(db)
}

func (qs BCSPodQuerySet) Select(fields ...BCSPodDBSchemaField) BCSPodQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(strings.Join(names, ",")))
}

// Create is an autogenerated method
// nolint: dupl
func (o *BCSPod) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *BCSPod) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) All(ret *[]BCSPod) error {
	return qs.db.Find(ret).Error
}

// BcsClusterIDEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDEq(bcsClusterID string) BCSPodQuerySet {
	return qs.w(qs.db.Where("bcs_cluster_id = ?", bcsClusterID))
}

// BcsClusterIDGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDGt(bcsClusterID string) BCSPodQuerySet {
	return qs.w(qs.db.Where("bcs_cluster_id > ?", bcsClusterID))
}

// BcsClusterIDGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDGte(bcsClusterID string) BCSPodQuerySet {
	return qs.w(qs.db.Where("bcs_cluster_id >= ?", bcsClusterID))
}

// BcsClusterIDIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDIn(bcsClusterID ...string) BCSPodQuerySet {
	if len(bcsClusterID) == 0 {
		qs.db.AddError(errors.New("must at least pass one bcsClusterID in BcsClusterIDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("bcs_cluster_id IN (?)", bcsClusterID))
}

// BcsClusterIDLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDLike(bcsClusterID string) BCSPodQuerySet {
	return qs.w(qs.db.Where("bcs_cluster_id LIKE ?", bcsClusterID))
}

// BcsClusterIDLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDLt(bcsClusterID string) BCSPodQuerySet {
	return qs.w(qs.db.Where("bcs_cluster_id < ?", bcsClusterID))
}

// BcsClusterIDLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDLte(bcsClusterID string) BCSPodQuerySet {
	return qs.w(qs.db.Where("bcs_cluster_id <= ?", bcsClusterID))
}

// BcsClusterIDNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDNe(bcsClusterID string) BCSPodQuerySet {
	return qs.w(qs.db.Where("bcs_cluster_id != ?", bcsClusterID))
}

// BcsClusterIDNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDNotIn(bcsClusterID ...string) BCSPodQuerySet {
	if len(bcsClusterID) == 0 {
		qs.db.AddError(errors.New("must at least pass one bcsClusterID in BcsClusterIDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("bcs_cluster_id NOT IN (?)", bcsClusterID))
}

// BcsClusterIDNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BcsClusterIDNotlike(bcsClusterID string) BCSPodQuerySet {
	return qs.w(qs.db.Where("bcs_cluster_id NOT LIKE ?", bcsClusterID))
}

// BkBizIdEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BkBizIdEq(bkBizId int) BCSPodQuerySet {
	return qs.w(qs.db.Where("bk_biz_id = ?", bkBizId))
}

// BkBizIdGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BkBizIdGt(bkBizId int) BCSPodQuerySet {
	return qs.w(qs.db.Where("bk_biz_id > ?", bkBizId))
}

// BkBizIdGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BkBizIdGte(bkBizId int) BCSPodQuerySet {
	return qs.w(qs.db.Where("bk_biz_id >= ?", bkBizId))
}

// BkBizIdIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BkBizIdIn(bkBizId ...int) BCSPodQuerySet {
	if len(bkBizId) == 0 {
		qs.db.AddError(errors.New("must at least pass one bkBizId in BkBizIdIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("bk_biz_id IN (?)", bkBizId))
}

// BkBizIdLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BkBizIdLt(bkBizId int) BCSPodQuerySet {
	return qs.w(qs.db.Where("bk_biz_id < ?", bkBizId))
}

// BkBizIdLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BkBizIdLte(bkBizId int) BCSPodQuerySet {
	return qs.w(qs.db.Where("bk_biz_id <= ?", bkBizId))
}

// BkBizIdNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BkBizIdNe(bkBizId int) BCSPodQuerySet {
	return qs.w(qs.db.Where("bk_biz_id != ?", bkBizId))
}

// BkBizIdNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) BkBizIdNotIn(bkBizId ...int) BCSPodQuerySet {
	if len(bkBizId) == 0 {
		qs.db.AddError(errors.New("must at least pass one bkBizId in BkBizIdNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("bk_biz_id NOT IN (?)", bkBizId))
}

// Count is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// CreateAtEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) CreateAtEq(createAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("create_at = ?", createAt))
}

// CreateAtGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) CreateAtGt(createAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("create_at > ?", createAt))
}

// CreateAtGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) CreateAtGte(createAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("create_at >= ?", createAt))
}

// CreateAtLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) CreateAtLt(createAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("create_at < ?", createAt))
}

// CreateAtLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) CreateAtLte(createAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("create_at <= ?", createAt))
}

// CreateAtNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) CreateAtNe(createAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("create_at != ?", createAt))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) Delete() error {
	return qs.db.Delete(BCSPod{}).Error
}

// DeleteAtEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteAtEq(deleteAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("delete_at = ?", deleteAt))
}

// DeleteAtGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteAtGt(deleteAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("delete_at > ?", deleteAt))
}

// DeleteAtGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteAtGte(deleteAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("delete_at >= ?", deleteAt))
}

// DeleteAtIsNotNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteAtIsNotNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("delete_at IS NOT NULL"))
}

// DeleteAtIsNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteAtIsNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("delete_at IS NULL"))
}

// DeleteAtLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteAtLt(deleteAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("delete_at < ?", deleteAt))
}

// DeleteAtLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteAtLte(deleteAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("delete_at <= ?", deleteAt))
}

// DeleteAtNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteAtNe(deleteAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("delete_at != ?", deleteAt))
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(BCSPod{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(BCSPod{})
	return db.RowsAffected, db.Error
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) GetUpdater() BCSPodUpdater {
	return NewBCSPodUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) IDEq(ID uint) BCSPodQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) IDGt(ID uint) BCSPodQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) IDGte(ID uint) BCSPodQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) IDIn(ID ...uint) BCSPodQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id IN (?)", ID))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) IDLt(ID uint) BCSPodQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) IDLte(ID uint) BCSPodQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) IDNe(ID uint) BCSPodQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) IDNotIn(ID ...uint) BCSPodQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", ID))
}

// ImagesEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesEq(images string) BCSPodQuerySet {
	return qs.w(qs.db.Where("images = ?", images))
}

// ImagesGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesGt(images string) BCSPodQuerySet {
	return qs.w(qs.db.Where("images > ?", images))
}

// ImagesGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesGte(images string) BCSPodQuerySet {
	return qs.w(qs.db.Where("images >= ?", images))
}

// ImagesIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesIn(images ...string) BCSPodQuerySet {
	if len(images) == 0 {
		qs.db.AddError(errors.New("must at least pass one images in ImagesIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("images IN (?)", images))
}

// ImagesLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesLike(images string) BCSPodQuerySet {
	return qs.w(qs.db.Where("images LIKE ?", images))
}

// ImagesLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesLt(images string) BCSPodQuerySet {
	return qs.w(qs.db.Where("images < ?", images))
}

// ImagesLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesLte(images string) BCSPodQuerySet {
	return qs.w(qs.db.Where("images <= ?", images))
}

// ImagesNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesNe(images string) BCSPodQuerySet {
	return qs.w(qs.db.Where("images != ?", images))
}

// ImagesNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesNotIn(images ...string) BCSPodQuerySet {
	if len(images) == 0 {
		qs.db.AddError(errors.New("must at least pass one images in ImagesNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("images NOT IN (?)", images))
}

// ImagesNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ImagesNotlike(images string) BCSPodQuerySet {
	return qs.w(qs.db.Where("images NOT LIKE ?", images))
}

// LastSyncedAtEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LastSyncedAtEq(lastSyncedAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("last_synced_at = ?", lastSyncedAt))
}

// LastSyncedAtGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LastSyncedAtGt(lastSyncedAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("last_synced_at > ?", lastSyncedAt))
}

// LastSyncedAtGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LastSyncedAtGte(lastSyncedAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("last_synced_at >= ?", lastSyncedAt))
}

// LastSyncedAtLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LastSyncedAtLt(lastSyncedAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("last_synced_at < ?", lastSyncedAt))
}

// LastSyncedAtLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LastSyncedAtLte(lastSyncedAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("last_synced_at <= ?", lastSyncedAt))
}

// LastSyncedAtNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LastSyncedAtNe(lastSyncedAt time.Time) BCSPodQuerySet {
	return qs.w(qs.db.Where("last_synced_at != ?", lastSyncedAt))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) Limit(limit int) BCSPodQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// LimitCpuUsageRatioEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioEq(limitCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_cpu_usage_ratio = ?", limitCpuUsageRatio))
}

// LimitCpuUsageRatioGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioGt(limitCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_cpu_usage_ratio > ?", limitCpuUsageRatio))
}

// LimitCpuUsageRatioGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioGte(limitCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_cpu_usage_ratio >= ?", limitCpuUsageRatio))
}

// LimitCpuUsageRatioIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioIn(limitCpuUsageRatio ...float64) BCSPodQuerySet {
	if len(limitCpuUsageRatio) == 0 {
		qs.db.AddError(errors.New("must at least pass one limitCpuUsageRatio in LimitCpuUsageRatioIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("limit_cpu_usage_ratio IN (?)", limitCpuUsageRatio))
}

// LimitCpuUsageRatioIsNotNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioIsNotNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_cpu_usage_ratio IS NOT NULL"))
}

// LimitCpuUsageRatioIsNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioIsNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_cpu_usage_ratio IS NULL"))
}

// LimitCpuUsageRatioLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioLt(limitCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_cpu_usage_ratio < ?", limitCpuUsageRatio))
}

// LimitCpuUsageRatioLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioLte(limitCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_cpu_usage_ratio <= ?", limitCpuUsageRatio))
}

// LimitCpuUsageRatioNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioNe(limitCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_cpu_usage_ratio != ?", limitCpuUsageRatio))
}

// LimitCpuUsageRatioNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitCpuUsageRatioNotIn(limitCpuUsageRatio ...float64) BCSPodQuerySet {
	if len(limitCpuUsageRatio) == 0 {
		qs.db.AddError(errors.New("must at least pass one limitCpuUsageRatio in LimitCpuUsageRatioNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("limit_cpu_usage_ratio NOT IN (?)", limitCpuUsageRatio))
}

// LimitMemoryUsageRatioEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioEq(limitMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_memory_usage_ratio = ?", limitMemoryUsageRatio))
}

// LimitMemoryUsageRatioGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioGt(limitMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_memory_usage_ratio > ?", limitMemoryUsageRatio))
}

// LimitMemoryUsageRatioGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioGte(limitMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_memory_usage_ratio >= ?", limitMemoryUsageRatio))
}

// LimitMemoryUsageRatioIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioIn(limitMemoryUsageRatio ...float64) BCSPodQuerySet {
	if len(limitMemoryUsageRatio) == 0 {
		qs.db.AddError(errors.New("must at least pass one limitMemoryUsageRatio in LimitMemoryUsageRatioIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("limit_memory_usage_ratio IN (?)", limitMemoryUsageRatio))
}

// LimitMemoryUsageRatioIsNotNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioIsNotNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_memory_usage_ratio IS NOT NULL"))
}

// LimitMemoryUsageRatioIsNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioIsNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_memory_usage_ratio IS NULL"))
}

// LimitMemoryUsageRatioLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioLt(limitMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_memory_usage_ratio < ?", limitMemoryUsageRatio))
}

// LimitMemoryUsageRatioLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioLte(limitMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_memory_usage_ratio <= ?", limitMemoryUsageRatio))
}

// LimitMemoryUsageRatioNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioNe(limitMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("limit_memory_usage_ratio != ?", limitMemoryUsageRatio))
}

// LimitMemoryUsageRatioNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) LimitMemoryUsageRatioNotIn(limitMemoryUsageRatio ...float64) BCSPodQuerySet {
	if len(limitMemoryUsageRatio) == 0 {
		qs.db.AddError(errors.New("must at least pass one limitMemoryUsageRatio in LimitMemoryUsageRatioNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("limit_memory_usage_ratio NOT IN (?)", limitMemoryUsageRatio))
}

// MonitorStatusEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusEq(monitorStatus string) BCSPodQuerySet {
	return qs.w(qs.db.Where("monitor_status = ?", monitorStatus))
}

// MonitorStatusGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusGt(monitorStatus string) BCSPodQuerySet {
	return qs.w(qs.db.Where("monitor_status > ?", monitorStatus))
}

// MonitorStatusGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusGte(monitorStatus string) BCSPodQuerySet {
	return qs.w(qs.db.Where("monitor_status >= ?", monitorStatus))
}

// MonitorStatusIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusIn(monitorStatus ...string) BCSPodQuerySet {
	if len(monitorStatus) == 0 {
		qs.db.AddError(errors.New("must at least pass one monitorStatus in MonitorStatusIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("monitor_status IN (?)", monitorStatus))
}

// MonitorStatusLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusLike(monitorStatus string) BCSPodQuerySet {
	return qs.w(qs.db.Where("monitor_status LIKE ?", monitorStatus))
}

// MonitorStatusLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusLt(monitorStatus string) BCSPodQuerySet {
	return qs.w(qs.db.Where("monitor_status < ?", monitorStatus))
}

// MonitorStatusLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusLte(monitorStatus string) BCSPodQuerySet {
	return qs.w(qs.db.Where("monitor_status <= ?", monitorStatus))
}

// MonitorStatusNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusNe(monitorStatus string) BCSPodQuerySet {
	return qs.w(qs.db.Where("monitor_status != ?", monitorStatus))
}

// MonitorStatusNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusNotIn(monitorStatus ...string) BCSPodQuerySet {
	if len(monitorStatus) == 0 {
		qs.db.AddError(errors.New("must at least pass one monitorStatus in MonitorStatusNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("monitor_status NOT IN (?)", monitorStatus))
}

// MonitorStatusNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) MonitorStatusNotlike(monitorStatus string) BCSPodQuerySet {
	return qs.w(qs.db.Where("monitor_status NOT LIKE ?", monitorStatus))
}

// NameEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameEq(name string) BCSPodQuerySet {
	return qs.w(qs.db.Where("name = ?", name))
}

// NameGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameGt(name string) BCSPodQuerySet {
	return qs.w(qs.db.Where("name > ?", name))
}

// NameGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameGte(name string) BCSPodQuerySet {
	return qs.w(qs.db.Where("name >= ?", name))
}

// NameIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameIn(name ...string) BCSPodQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("name IN (?)", name))
}

// NameLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameLike(name string) BCSPodQuerySet {
	return qs.w(qs.db.Where("name LIKE ?", name))
}

// NameLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameLt(name string) BCSPodQuerySet {
	return qs.w(qs.db.Where("name < ?", name))
}

// NameLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameLte(name string) BCSPodQuerySet {
	return qs.w(qs.db.Where("name <= ?", name))
}

// NameNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameNe(name string) BCSPodQuerySet {
	return qs.w(qs.db.Where("name != ?", name))
}

// NameNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameNotIn(name ...string) BCSPodQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("name NOT IN (?)", name))
}

// NameNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NameNotlike(name string) BCSPodQuerySet {
	return qs.w(qs.db.Where("name NOT LIKE ?", name))
}

// NamespaceEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceEq(namespace string) BCSPodQuerySet {
	return qs.w(qs.db.Where("namespace = ?", namespace))
}

// NamespaceGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceGt(namespace string) BCSPodQuerySet {
	return qs.w(qs.db.Where("namespace > ?", namespace))
}

// NamespaceGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceGte(namespace string) BCSPodQuerySet {
	return qs.w(qs.db.Where("namespace >= ?", namespace))
}

// NamespaceIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceIn(namespace ...string) BCSPodQuerySet {
	if len(namespace) == 0 {
		qs.db.AddError(errors.New("must at least pass one namespace in NamespaceIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("namespace IN (?)", namespace))
}

// NamespaceLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceLike(namespace string) BCSPodQuerySet {
	return qs.w(qs.db.Where("namespace LIKE ?", namespace))
}

// NamespaceLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceLt(namespace string) BCSPodQuerySet {
	return qs.w(qs.db.Where("namespace < ?", namespace))
}

// NamespaceLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceLte(namespace string) BCSPodQuerySet {
	return qs.w(qs.db.Where("namespace <= ?", namespace))
}

// NamespaceNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceNe(namespace string) BCSPodQuerySet {
	return qs.w(qs.db.Where("namespace != ?", namespace))
}

// NamespaceNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceNotIn(namespace ...string) BCSPodQuerySet {
	if len(namespace) == 0 {
		qs.db.AddError(errors.New("must at least pass one namespace in NamespaceNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("namespace NOT IN (?)", namespace))
}

// NamespaceNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NamespaceNotlike(namespace string) BCSPodQuerySet {
	return qs.w(qs.db.Where("namespace NOT LIKE ?", namespace))
}

// NodeIpEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpEq(nodeIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_ip = ?", nodeIp))
}

// NodeIpGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpGt(nodeIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_ip > ?", nodeIp))
}

// NodeIpGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpGte(nodeIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_ip >= ?", nodeIp))
}

// NodeIpIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpIn(nodeIp ...string) BCSPodQuerySet {
	if len(nodeIp) == 0 {
		qs.db.AddError(errors.New("must at least pass one nodeIp in NodeIpIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("node_ip IN (?)", nodeIp))
}

// NodeIpLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpLike(nodeIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_ip LIKE ?", nodeIp))
}

// NodeIpLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpLt(nodeIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_ip < ?", nodeIp))
}

// NodeIpLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpLte(nodeIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_ip <= ?", nodeIp))
}

// NodeIpNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpNe(nodeIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_ip != ?", nodeIp))
}

// NodeIpNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpNotIn(nodeIp ...string) BCSPodQuerySet {
	if len(nodeIp) == 0 {
		qs.db.AddError(errors.New("must at least pass one nodeIp in NodeIpNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("node_ip NOT IN (?)", nodeIp))
}

// NodeIpNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeIpNotlike(nodeIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_ip NOT LIKE ?", nodeIp))
}

// NodeNameEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameEq(nodeName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_name = ?", nodeName))
}

// NodeNameGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameGt(nodeName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_name > ?", nodeName))
}

// NodeNameGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameGte(nodeName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_name >= ?", nodeName))
}

// NodeNameIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameIn(nodeName ...string) BCSPodQuerySet {
	if len(nodeName) == 0 {
		qs.db.AddError(errors.New("must at least pass one nodeName in NodeNameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("node_name IN (?)", nodeName))
}

// NodeNameLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameLike(nodeName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_name LIKE ?", nodeName))
}

// NodeNameLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameLt(nodeName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_name < ?", nodeName))
}

// NodeNameLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameLte(nodeName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_name <= ?", nodeName))
}

// NodeNameNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameNe(nodeName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_name != ?", nodeName))
}

// NodeNameNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameNotIn(nodeName ...string) BCSPodQuerySet {
	if len(nodeName) == 0 {
		qs.db.AddError(errors.New("must at least pass one nodeName in NodeNameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("node_name NOT IN (?)", nodeName))
}

// NodeNameNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) NodeNameNotlike(nodeName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("node_name NOT LIKE ?", nodeName))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) Offset(offset int) BCSPodQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs BCSPodQuerySet) One(ret *BCSPod) error {
	return qs.db.First(ret).Error
}

// OrderAscByBcsClusterID is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByBcsClusterID() BCSPodQuerySet {
	return qs.w(qs.db.Order("bcs_cluster_id ASC"))
}

// OrderAscByBkBizId is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByBkBizId() BCSPodQuerySet {
	return qs.w(qs.db.Order("bk_biz_id ASC"))
}

// OrderAscByCreateAt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByCreateAt() BCSPodQuerySet {
	return qs.w(qs.db.Order("create_at ASC"))
}

// OrderAscByDeleteAt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByDeleteAt() BCSPodQuerySet {
	return qs.w(qs.db.Order("delete_at ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByID() BCSPodQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByImages is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByImages() BCSPodQuerySet {
	return qs.w(qs.db.Order("images ASC"))
}

// OrderAscByLastSyncedAt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByLastSyncedAt() BCSPodQuerySet {
	return qs.w(qs.db.Order("last_synced_at ASC"))
}

// OrderAscByLimitCpuUsageRatio is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByLimitCpuUsageRatio() BCSPodQuerySet {
	return qs.w(qs.db.Order("limit_cpu_usage_ratio ASC"))
}

// OrderAscByLimitMemoryUsageRatio is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByLimitMemoryUsageRatio() BCSPodQuerySet {
	return qs.w(qs.db.Order("limit_memory_usage_ratio ASC"))
}

// OrderAscByMonitorStatus is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByMonitorStatus() BCSPodQuerySet {
	return qs.w(qs.db.Order("monitor_status ASC"))
}

// OrderAscByName is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByName() BCSPodQuerySet {
	return qs.w(qs.db.Order("name ASC"))
}

// OrderAscByNamespace is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByNamespace() BCSPodQuerySet {
	return qs.w(qs.db.Order("namespace ASC"))
}

// OrderAscByNodeIp is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByNodeIp() BCSPodQuerySet {
	return qs.w(qs.db.Order("node_ip ASC"))
}

// OrderAscByNodeName is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByNodeName() BCSPodQuerySet {
	return qs.w(qs.db.Order("node_name ASC"))
}

// OrderAscByPodIp is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByPodIp() BCSPodQuerySet {
	return qs.w(qs.db.Order("pod_ip ASC"))
}

// OrderAscByReadyContainerCount is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByReadyContainerCount() BCSPodQuerySet {
	return qs.w(qs.db.Order("ready_container_count ASC"))
}

// OrderAscByRequestCpuUsageRatio is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByRequestCpuUsageRatio() BCSPodQuerySet {
	return qs.w(qs.db.Order("request_cpu_usage_ratio ASC"))
}

// OrderAscByRequestMemoryUsageRatio is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByRequestMemoryUsageRatio() BCSPodQuerySet {
	return qs.w(qs.db.Order("request_memory_usage_ratio ASC"))
}

// OrderAscByRestarts is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByRestarts() BCSPodQuerySet {
	return qs.w(qs.db.Order("restarts ASC"))
}

// OrderAscByStatus is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByStatus() BCSPodQuerySet {
	return qs.w(qs.db.Order("status ASC"))
}

// OrderAscByTotalContainerCount is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByTotalContainerCount() BCSPodQuerySet {
	return qs.w(qs.db.Order("total_container_count ASC"))
}

// OrderAscByUniqueHash is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByUniqueHash() BCSPodQuerySet {
	return qs.w(qs.db.Order("unique_hash ASC"))
}

// OrderAscByWorkloadName is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByWorkloadName() BCSPodQuerySet {
	return qs.w(qs.db.Order("workload_name ASC"))
}

// OrderAscByWorkloadType is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderAscByWorkloadType() BCSPodQuerySet {
	return qs.w(qs.db.Order("workload_type ASC"))
}

// OrderDescByBcsClusterID is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByBcsClusterID() BCSPodQuerySet {
	return qs.w(qs.db.Order("bcs_cluster_id DESC"))
}

// OrderDescByBkBizId is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByBkBizId() BCSPodQuerySet {
	return qs.w(qs.db.Order("bk_biz_id DESC"))
}

// OrderDescByCreateAt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByCreateAt() BCSPodQuerySet {
	return qs.w(qs.db.Order("create_at DESC"))
}

// OrderDescByDeleteAt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByDeleteAt() BCSPodQuerySet {
	return qs.w(qs.db.Order("delete_at DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByID() BCSPodQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByImages is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByImages() BCSPodQuerySet {
	return qs.w(qs.db.Order("images DESC"))
}

// OrderDescByLastSyncedAt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByLastSyncedAt() BCSPodQuerySet {
	return qs.w(qs.db.Order("last_synced_at DESC"))
}

// OrderDescByLimitCpuUsageRatio is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByLimitCpuUsageRatio() BCSPodQuerySet {
	return qs.w(qs.db.Order("limit_cpu_usage_ratio DESC"))
}

// OrderDescByLimitMemoryUsageRatio is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByLimitMemoryUsageRatio() BCSPodQuerySet {
	return qs.w(qs.db.Order("limit_memory_usage_ratio DESC"))
}

// OrderDescByMonitorStatus is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByMonitorStatus() BCSPodQuerySet {
	return qs.w(qs.db.Order("monitor_status DESC"))
}

// OrderDescByName is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByName() BCSPodQuerySet {
	return qs.w(qs.db.Order("name DESC"))
}

// OrderDescByNamespace is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByNamespace() BCSPodQuerySet {
	return qs.w(qs.db.Order("namespace DESC"))
}

// OrderDescByNodeIp is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByNodeIp() BCSPodQuerySet {
	return qs.w(qs.db.Order("node_ip DESC"))
}

// OrderDescByNodeName is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByNodeName() BCSPodQuerySet {
	return qs.w(qs.db.Order("node_name DESC"))
}

// OrderDescByPodIp is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByPodIp() BCSPodQuerySet {
	return qs.w(qs.db.Order("pod_ip DESC"))
}

// OrderDescByReadyContainerCount is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByReadyContainerCount() BCSPodQuerySet {
	return qs.w(qs.db.Order("ready_container_count DESC"))
}

// OrderDescByRequestCpuUsageRatio is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByRequestCpuUsageRatio() BCSPodQuerySet {
	return qs.w(qs.db.Order("request_cpu_usage_ratio DESC"))
}

// OrderDescByRequestMemoryUsageRatio is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByRequestMemoryUsageRatio() BCSPodQuerySet {
	return qs.w(qs.db.Order("request_memory_usage_ratio DESC"))
}

// OrderDescByRestarts is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByRestarts() BCSPodQuerySet {
	return qs.w(qs.db.Order("restarts DESC"))
}

// OrderDescByStatus is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByStatus() BCSPodQuerySet {
	return qs.w(qs.db.Order("status DESC"))
}

// OrderDescByTotalContainerCount is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByTotalContainerCount() BCSPodQuerySet {
	return qs.w(qs.db.Order("total_container_count DESC"))
}

// OrderDescByUniqueHash is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByUniqueHash() BCSPodQuerySet {
	return qs.w(qs.db.Order("unique_hash DESC"))
}

// OrderDescByWorkloadName is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByWorkloadName() BCSPodQuerySet {
	return qs.w(qs.db.Order("workload_name DESC"))
}

// OrderDescByWorkloadType is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) OrderDescByWorkloadType() BCSPodQuerySet {
	return qs.w(qs.db.Order("workload_type DESC"))
}

// PodIpEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpEq(podIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("pod_ip = ?", podIp))
}

// PodIpGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpGt(podIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("pod_ip > ?", podIp))
}

// PodIpGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpGte(podIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("pod_ip >= ?", podIp))
}

// PodIpIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpIn(podIp ...string) BCSPodQuerySet {
	if len(podIp) == 0 {
		qs.db.AddError(errors.New("must at least pass one podIp in PodIpIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("pod_ip IN (?)", podIp))
}

// PodIpLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpLike(podIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("pod_ip LIKE ?", podIp))
}

// PodIpLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpLt(podIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("pod_ip < ?", podIp))
}

// PodIpLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpLte(podIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("pod_ip <= ?", podIp))
}

// PodIpNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpNe(podIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("pod_ip != ?", podIp))
}

// PodIpNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpNotIn(podIp ...string) BCSPodQuerySet {
	if len(podIp) == 0 {
		qs.db.AddError(errors.New("must at least pass one podIp in PodIpNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("pod_ip NOT IN (?)", podIp))
}

// PodIpNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) PodIpNotlike(podIp string) BCSPodQuerySet {
	return qs.w(qs.db.Where("pod_ip NOT LIKE ?", podIp))
}

// ReadyContainerCountEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ReadyContainerCountEq(readyContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("ready_container_count = ?", readyContainerCount))
}

// ReadyContainerCountGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ReadyContainerCountGt(readyContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("ready_container_count > ?", readyContainerCount))
}

// ReadyContainerCountGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ReadyContainerCountGte(readyContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("ready_container_count >= ?", readyContainerCount))
}

// ReadyContainerCountIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ReadyContainerCountIn(readyContainerCount ...int) BCSPodQuerySet {
	if len(readyContainerCount) == 0 {
		qs.db.AddError(errors.New("must at least pass one readyContainerCount in ReadyContainerCountIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("ready_container_count IN (?)", readyContainerCount))
}

// ReadyContainerCountLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ReadyContainerCountLt(readyContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("ready_container_count < ?", readyContainerCount))
}

// ReadyContainerCountLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ReadyContainerCountLte(readyContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("ready_container_count <= ?", readyContainerCount))
}

// ReadyContainerCountNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ReadyContainerCountNe(readyContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("ready_container_count != ?", readyContainerCount))
}

// ReadyContainerCountNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) ReadyContainerCountNotIn(readyContainerCount ...int) BCSPodQuerySet {
	if len(readyContainerCount) == 0 {
		qs.db.AddError(errors.New("must at least pass one readyContainerCount in ReadyContainerCountNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("ready_container_count NOT IN (?)", readyContainerCount))
}

// RequestCpuUsageRatioEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioEq(requestCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_cpu_usage_ratio = ?", requestCpuUsageRatio))
}

// RequestCpuUsageRatioGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioGt(requestCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_cpu_usage_ratio > ?", requestCpuUsageRatio))
}

// RequestCpuUsageRatioGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioGte(requestCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_cpu_usage_ratio >= ?", requestCpuUsageRatio))
}

// RequestCpuUsageRatioIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioIn(requestCpuUsageRatio ...float64) BCSPodQuerySet {
	if len(requestCpuUsageRatio) == 0 {
		qs.db.AddError(errors.New("must at least pass one requestCpuUsageRatio in RequestCpuUsageRatioIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("request_cpu_usage_ratio IN (?)", requestCpuUsageRatio))
}

// RequestCpuUsageRatioIsNotNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioIsNotNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("request_cpu_usage_ratio IS NOT NULL"))
}

// RequestCpuUsageRatioIsNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioIsNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("request_cpu_usage_ratio IS NULL"))
}

// RequestCpuUsageRatioLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioLt(requestCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_cpu_usage_ratio < ?", requestCpuUsageRatio))
}

// RequestCpuUsageRatioLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioLte(requestCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_cpu_usage_ratio <= ?", requestCpuUsageRatio))
}

// RequestCpuUsageRatioNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioNe(requestCpuUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_cpu_usage_ratio != ?", requestCpuUsageRatio))
}

// RequestCpuUsageRatioNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestCpuUsageRatioNotIn(requestCpuUsageRatio ...float64) BCSPodQuerySet {
	if len(requestCpuUsageRatio) == 0 {
		qs.db.AddError(errors.New("must at least pass one requestCpuUsageRatio in RequestCpuUsageRatioNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("request_cpu_usage_ratio NOT IN (?)", requestCpuUsageRatio))
}

// RequestMemoryUsageRatioEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioEq(requestMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_memory_usage_ratio = ?", requestMemoryUsageRatio))
}

// RequestMemoryUsageRatioGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioGt(requestMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_memory_usage_ratio > ?", requestMemoryUsageRatio))
}

// RequestMemoryUsageRatioGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioGte(requestMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_memory_usage_ratio >= ?", requestMemoryUsageRatio))
}

// RequestMemoryUsageRatioIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioIn(requestMemoryUsageRatio ...float64) BCSPodQuerySet {
	if len(requestMemoryUsageRatio) == 0 {
		qs.db.AddError(errors.New("must at least pass one requestMemoryUsageRatio in RequestMemoryUsageRatioIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("request_memory_usage_ratio IN (?)", requestMemoryUsageRatio))
}

// RequestMemoryUsageRatioIsNotNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioIsNotNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("request_memory_usage_ratio IS NOT NULL"))
}

// RequestMemoryUsageRatioIsNull is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioIsNull() BCSPodQuerySet {
	return qs.w(qs.db.Where("request_memory_usage_ratio IS NULL"))
}

// RequestMemoryUsageRatioLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioLt(requestMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_memory_usage_ratio < ?", requestMemoryUsageRatio))
}

// RequestMemoryUsageRatioLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioLte(requestMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_memory_usage_ratio <= ?", requestMemoryUsageRatio))
}

// RequestMemoryUsageRatioNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioNe(requestMemoryUsageRatio float64) BCSPodQuerySet {
	return qs.w(qs.db.Where("request_memory_usage_ratio != ?", requestMemoryUsageRatio))
}

// RequestMemoryUsageRatioNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RequestMemoryUsageRatioNotIn(requestMemoryUsageRatio ...float64) BCSPodQuerySet {
	if len(requestMemoryUsageRatio) == 0 {
		qs.db.AddError(errors.New("must at least pass one requestMemoryUsageRatio in RequestMemoryUsageRatioNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("request_memory_usage_ratio NOT IN (?)", requestMemoryUsageRatio))
}

// RestartsEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RestartsEq(restarts int) BCSPodQuerySet {
	return qs.w(qs.db.Where("restarts = ?", restarts))
}

// RestartsGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RestartsGt(restarts int) BCSPodQuerySet {
	return qs.w(qs.db.Where("restarts > ?", restarts))
}

// RestartsGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RestartsGte(restarts int) BCSPodQuerySet {
	return qs.w(qs.db.Where("restarts >= ?", restarts))
}

// RestartsIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RestartsIn(restarts ...int) BCSPodQuerySet {
	if len(restarts) == 0 {
		qs.db.AddError(errors.New("must at least pass one restarts in RestartsIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("restarts IN (?)", restarts))
}

// RestartsLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RestartsLt(restarts int) BCSPodQuerySet {
	return qs.w(qs.db.Where("restarts < ?", restarts))
}

// RestartsLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RestartsLte(restarts int) BCSPodQuerySet {
	return qs.w(qs.db.Where("restarts <= ?", restarts))
}

// RestartsNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RestartsNe(restarts int) BCSPodQuerySet {
	return qs.w(qs.db.Where("restarts != ?", restarts))
}

// RestartsNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) RestartsNotIn(restarts ...int) BCSPodQuerySet {
	if len(restarts) == 0 {
		qs.db.AddError(errors.New("must at least pass one restarts in RestartsNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("restarts NOT IN (?)", restarts))
}

// StatusEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusEq(status string) BCSPodQuerySet {
	return qs.w(qs.db.Where("status = ?", status))
}

// StatusGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusGt(status string) BCSPodQuerySet {
	return qs.w(qs.db.Where("status > ?", status))
}

// StatusGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusGte(status string) BCSPodQuerySet {
	return qs.w(qs.db.Where("status >= ?", status))
}

// StatusIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusIn(status ...string) BCSPodQuerySet {
	if len(status) == 0 {
		qs.db.AddError(errors.New("must at least pass one status in StatusIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("status IN (?)", status))
}

// StatusLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusLike(status string) BCSPodQuerySet {
	return qs.w(qs.db.Where("status LIKE ?", status))
}

// StatusLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusLt(status string) BCSPodQuerySet {
	return qs.w(qs.db.Where("status < ?", status))
}

// StatusLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusLte(status string) BCSPodQuerySet {
	return qs.w(qs.db.Where("status <= ?", status))
}

// StatusNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusNe(status string) BCSPodQuerySet {
	return qs.w(qs.db.Where("status != ?", status))
}

// StatusNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusNotIn(status ...string) BCSPodQuerySet {
	if len(status) == 0 {
		qs.db.AddError(errors.New("must at least pass one status in StatusNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("status NOT IN (?)", status))
}

// StatusNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) StatusNotlike(status string) BCSPodQuerySet {
	return qs.w(qs.db.Where("status NOT LIKE ?", status))
}

// TotalContainerCountEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) TotalContainerCountEq(totalContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("total_container_count = ?", totalContainerCount))
}

// TotalContainerCountGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) TotalContainerCountGt(totalContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("total_container_count > ?", totalContainerCount))
}

// TotalContainerCountGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) TotalContainerCountGte(totalContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("total_container_count >= ?", totalContainerCount))
}

// TotalContainerCountIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) TotalContainerCountIn(totalContainerCount ...int) BCSPodQuerySet {
	if len(totalContainerCount) == 0 {
		qs.db.AddError(errors.New("must at least pass one totalContainerCount in TotalContainerCountIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("total_container_count IN (?)", totalContainerCount))
}

// TotalContainerCountLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) TotalContainerCountLt(totalContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("total_container_count < ?", totalContainerCount))
}

// TotalContainerCountLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) TotalContainerCountLte(totalContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("total_container_count <= ?", totalContainerCount))
}

// TotalContainerCountNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) TotalContainerCountNe(totalContainerCount int) BCSPodQuerySet {
	return qs.w(qs.db.Where("total_container_count != ?", totalContainerCount))
}

// TotalContainerCountNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) TotalContainerCountNotIn(totalContainerCount ...int) BCSPodQuerySet {
	if len(totalContainerCount) == 0 {
		qs.db.AddError(errors.New("must at least pass one totalContainerCount in TotalContainerCountNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("total_container_count NOT IN (?)", totalContainerCount))
}

// UniqueHashEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashEq(uniqueHash string) BCSPodQuerySet {
	return qs.w(qs.db.Where("unique_hash = ?", uniqueHash))
}

// UniqueHashGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashGt(uniqueHash string) BCSPodQuerySet {
	return qs.w(qs.db.Where("unique_hash > ?", uniqueHash))
}

// UniqueHashGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashGte(uniqueHash string) BCSPodQuerySet {
	return qs.w(qs.db.Where("unique_hash >= ?", uniqueHash))
}

// UniqueHashIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashIn(uniqueHash ...string) BCSPodQuerySet {
	if len(uniqueHash) == 0 {
		qs.db.AddError(errors.New("must at least pass one uniqueHash in UniqueHashIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("unique_hash IN (?)", uniqueHash))
}

// UniqueHashLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashLike(uniqueHash string) BCSPodQuerySet {
	return qs.w(qs.db.Where("unique_hash LIKE ?", uniqueHash))
}

// UniqueHashLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashLt(uniqueHash string) BCSPodQuerySet {
	return qs.w(qs.db.Where("unique_hash < ?", uniqueHash))
}

// UniqueHashLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashLte(uniqueHash string) BCSPodQuerySet {
	return qs.w(qs.db.Where("unique_hash <= ?", uniqueHash))
}

// UniqueHashNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashNe(uniqueHash string) BCSPodQuerySet {
	return qs.w(qs.db.Where("unique_hash != ?", uniqueHash))
}

// UniqueHashNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashNotIn(uniqueHash ...string) BCSPodQuerySet {
	if len(uniqueHash) == 0 {
		qs.db.AddError(errors.New("must at least pass one uniqueHash in UniqueHashNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("unique_hash NOT IN (?)", uniqueHash))
}

// UniqueHashNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) UniqueHashNotlike(uniqueHash string) BCSPodQuerySet {
	return qs.w(qs.db.Where("unique_hash NOT LIKE ?", uniqueHash))
}

// WorkloadNameEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameEq(workloadName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_name = ?", workloadName))
}

// WorkloadNameGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameGt(workloadName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_name > ?", workloadName))
}

// WorkloadNameGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameGte(workloadName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_name >= ?", workloadName))
}

// WorkloadNameIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameIn(workloadName ...string) BCSPodQuerySet {
	if len(workloadName) == 0 {
		qs.db.AddError(errors.New("must at least pass one workloadName in WorkloadNameIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("workload_name IN (?)", workloadName))
}

// WorkloadNameLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameLike(workloadName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_name LIKE ?", workloadName))
}

// WorkloadNameLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameLt(workloadName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_name < ?", workloadName))
}

// WorkloadNameLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameLte(workloadName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_name <= ?", workloadName))
}

// WorkloadNameNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameNe(workloadName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_name != ?", workloadName))
}

// WorkloadNameNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameNotIn(workloadName ...string) BCSPodQuerySet {
	if len(workloadName) == 0 {
		qs.db.AddError(errors.New("must at least pass one workloadName in WorkloadNameNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("workload_name NOT IN (?)", workloadName))
}

// WorkloadNameNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadNameNotlike(workloadName string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_name NOT LIKE ?", workloadName))
}

// WorkloadTypeEq is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeEq(workloadType string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_type = ?", workloadType))
}

// WorkloadTypeGt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeGt(workloadType string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_type > ?", workloadType))
}

// WorkloadTypeGte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeGte(workloadType string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_type >= ?", workloadType))
}

// WorkloadTypeIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeIn(workloadType ...string) BCSPodQuerySet {
	if len(workloadType) == 0 {
		qs.db.AddError(errors.New("must at least pass one workloadType in WorkloadTypeIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("workload_type IN (?)", workloadType))
}

// WorkloadTypeLike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeLike(workloadType string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_type LIKE ?", workloadType))
}

// WorkloadTypeLt is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeLt(workloadType string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_type < ?", workloadType))
}

// WorkloadTypeLte is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeLte(workloadType string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_type <= ?", workloadType))
}

// WorkloadTypeNe is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeNe(workloadType string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_type != ?", workloadType))
}

// WorkloadTypeNotIn is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeNotIn(workloadType ...string) BCSPodQuerySet {
	if len(workloadType) == 0 {
		qs.db.AddError(errors.New("must at least pass one workloadType in WorkloadTypeNotIn"))
		return qs.w(qs.db)
	}
	return qs.w(qs.db.Where("workload_type NOT IN (?)", workloadType))
}

// WorkloadTypeNotlike is an autogenerated method
// nolint: dupl
func (qs BCSPodQuerySet) WorkloadTypeNotlike(workloadType string) BCSPodQuerySet {
	return qs.w(qs.db.Where("workload_type NOT LIKE ?", workloadType))
}

// SetBcsClusterID is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetBcsClusterID(bcsClusterID string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.BcsClusterID)] = bcsClusterID
	return u
}

// SetBkBizId is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetBkBizId(bkBizId int) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.BkBizId)] = bkBizId
	return u
}

// SetCreateAt is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetCreateAt(createAt time.Time) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.CreateAt)] = createAt
	return u
}

// SetDeleteAt is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetDeleteAt(deleteAt *time.Time) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.DeleteAt)] = deleteAt
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetID(ID uint) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.ID)] = ID
	return u
}

// SetImages is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetImages(images string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.Images)] = images
	return u
}

// SetLastSyncedAt is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetLastSyncedAt(lastSyncedAt time.Time) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.LastSyncedAt)] = lastSyncedAt
	return u
}

// SetLimitCpuUsageRatio is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetLimitCpuUsageRatio(limitCpuUsageRatio *float64) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.LimitCpuUsageRatio)] = limitCpuUsageRatio
	return u
}

// SetLimitMemoryUsageRatio is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetLimitMemoryUsageRatio(limitMemoryUsageRatio *float64) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.LimitMemoryUsageRatio)] = limitMemoryUsageRatio
	return u
}

// SetMonitorStatus is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetMonitorStatus(monitorStatus string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.MonitorStatus)] = monitorStatus
	return u
}

// SetName is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetName(name string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.Name)] = name
	return u
}

// SetNamespace is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetNamespace(namespace string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.Namespace)] = namespace
	return u
}

// SetNodeIp is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetNodeIp(nodeIp string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.NodeIp)] = nodeIp
	return u
}

// SetNodeName is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetNodeName(nodeName string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.NodeName)] = nodeName
	return u
}

// SetPodIp is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetPodIp(podIp string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.PodIp)] = podIp
	return u
}

// SetReadyContainerCount is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetReadyContainerCount(readyContainerCount int) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.ReadyContainerCount)] = readyContainerCount
	return u
}

// SetRequestCpuUsageRatio is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetRequestCpuUsageRatio(requestCpuUsageRatio *float64) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.RequestCpuUsageRatio)] = requestCpuUsageRatio
	return u
}

// SetRequestMemoryUsageRatio is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetRequestMemoryUsageRatio(requestMemoryUsageRatio *float64) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.RequestMemoryUsageRatio)] = requestMemoryUsageRatio
	return u
}

// SetRestarts is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetRestarts(restarts int) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.Restarts)] = restarts
	return u
}

// SetStatus is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetStatus(status string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.Status)] = status
	return u
}

// SetTotalContainerCount is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetTotalContainerCount(totalContainerCount int) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.TotalContainerCount)] = totalContainerCount
	return u
}

// SetUniqueHash is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetUniqueHash(uniqueHash string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.UniqueHash)] = uniqueHash
	return u
}

// SetWorkloadName is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetWorkloadName(workloadName string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.WorkloadName)] = workloadName
	return u
}

// SetWorkloadType is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) SetWorkloadType(workloadType string) BCSPodUpdater {
	u.fields[string(BCSPodDBSchema.WorkloadType)] = workloadType
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u BCSPodUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set BCSPodQuerySet

// ===== BEGIN of BCSPod modifiers

// BCSPodDBSchemaField describes database schema field. It requires for method 'Update'
type BCSPodDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f BCSPodDBSchemaField) String() string {
	return string(f)
}

// BCSPodDBSchema stores db field names of BCSPod
var BCSPodDBSchema = struct {
	BcsClusterID            BCSPodDBSchemaField
	BkBizId                 BCSPodDBSchemaField
	CreateAt                BCSPodDBSchemaField
	DeleteAt                BCSPodDBSchemaField
	Status                  BCSPodDBSchemaField
	MonitorStatus           BCSPodDBSchemaField
	LastSyncedAt            BCSPodDBSchemaField
	UniqueHash              BCSPodDBSchemaField
	ID                      BCSPodDBSchemaField
	Name                    BCSPodDBSchemaField
	Namespace               BCSPodDBSchemaField
	NodeName                BCSPodDBSchemaField
	NodeIp                  BCSPodDBSchemaField
	WorkloadType            BCSPodDBSchemaField
	WorkloadName            BCSPodDBSchemaField
	TotalContainerCount     BCSPodDBSchemaField
	ReadyContainerCount     BCSPodDBSchemaField
	PodIp                   BCSPodDBSchemaField
	Images                  BCSPodDBSchemaField
	Restarts                BCSPodDBSchemaField
	RequestCpuUsageRatio    BCSPodDBSchemaField
	LimitCpuUsageRatio      BCSPodDBSchemaField
	RequestMemoryUsageRatio BCSPodDBSchemaField
	LimitMemoryUsageRatio   BCSPodDBSchemaField
}{

	BcsClusterID:            BCSPodDBSchemaField("bcs_cluster_id"),
	BkBizId:                 BCSPodDBSchemaField("bk_biz_id"),
	CreateAt:                BCSPodDBSchemaField("create_at"),
	DeleteAt:                BCSPodDBSchemaField("delete_at"),
	Status:                  BCSPodDBSchemaField("status"),
	MonitorStatus:           BCSPodDBSchemaField("monitor_status"),
	LastSyncedAt:            BCSPodDBSchemaField("last_synced_at"),
	UniqueHash:              BCSPodDBSchemaField("unique_hash"),
	ID:                      BCSPodDBSchemaField("id"),
	Name:                    BCSPodDBSchemaField("name"),
	Namespace:               BCSPodDBSchemaField("namespace"),
	NodeName:                BCSPodDBSchemaField("node_name"),
	NodeIp:                  BCSPodDBSchemaField("node_ip"),
	WorkloadType:            BCSPodDBSchemaField("workload_type"),
	WorkloadName:            BCSPodDBSchemaField("workload_name"),
	TotalContainerCount:     BCSPodDBSchemaField("total_container_count"),
	ReadyContainerCount:     BCSPodDBSchemaField("ready_container_count"),
	PodIp:                   BCSPodDBSchemaField("pod_ip"),
	Images:                  BCSPodDBSchemaField("images"),
	Restarts:                BCSPodDBSchemaField("restarts"),
	RequestCpuUsageRatio:    BCSPodDBSchemaField("request_cpu_usage_ratio"),
	LimitCpuUsageRatio:      BCSPodDBSchemaField("limit_cpu_usage_ratio"),
	RequestMemoryUsageRatio: BCSPodDBSchemaField("request_memory_usage_ratio"),
	LimitMemoryUsageRatio:   BCSPodDBSchemaField("limit_memory_usage_ratio"),
}

// Update updates BCSPod fields by primary key
// nolint: dupl
func (o *BCSPod) Update(db *gorm.DB, fields ...BCSPodDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"bcs_cluster_id":             o.BcsClusterID,
		"bk_biz_id":                  o.BkBizId,
		"create_at":                  o.CreateAt,
		"delete_at":                  o.DeleteAt,
		"status":                     o.Status,
		"monitor_status":             o.MonitorStatus,
		"last_synced_at":             o.LastSyncedAt,
		"unique_hash":                o.UniqueHash,
		"id":                         o.ID,
		"name":                       o.Name,
		"namespace":                  o.Namespace,
		"node_name":                  o.NodeName,
		"node_ip":                    o.NodeIp,
		"workload_type":              o.WorkloadType,
		"workload_name":              o.WorkloadName,
		"total_container_count":      o.TotalContainerCount,
		"ready_container_count":      o.ReadyContainerCount,
		"pod_ip":                     o.PodIp,
		"images":                     o.Images,
		"restarts":                   o.Restarts,
		"request_cpu_usage_ratio":    o.RequestCpuUsageRatio,
		"limit_cpu_usage_ratio":      o.LimitCpuUsageRatio,
		"request_memory_usage_ratio": o.RequestMemoryUsageRatio,
		"limit_memory_usage_ratio":   o.LimitMemoryUsageRatio,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update BCSPod %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// BCSPodUpdater is an BCSPod updates manager
type BCSPodUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewBCSPodUpdater creates new BCSPod updater
// nolint: dupl
func NewBCSPodUpdater(db *gorm.DB) BCSPodUpdater {
	return BCSPodUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&BCSPod{}),
	}
}

// ===== END of BCSPod modifiers

// ===== END of all query sets
